config/routes.rb
SimpleCommunity::Engine.routes.draw do
  resources :comments


  resources :posts do
  	resources :comments
  end

  root :to => "posts#index"
end

app/models/simple_community/comment.rb
module SimpleCommunity
  class Comment < ActiveRecord::Base
    attr_accessible :content, :post_id, :user_id, :verified
    belongs_to :user
    belongs_to :post
  end
end

app/models/simple_community/post.rb
module SimpleCommunity
  class Post < ActiveRecord::Base
    attr_accessible :content, :name, :user_id, :verified, :youtube_id
    has_many :comments
    belongs_to :user
    has_and_belongs_to_many :images, :join_table => "simple_image_bank_images_simple_community_posts", :class_name => "SimpleImageBank::Image"

    validates :name, :length => { :minimum => 3 }
    validates :content, :length => { :minimum => 10 }

    def is_owner?(user_id)
	  true
    end
  end
end

app/models/simple_community/user.rb
module SimpleCommunity
  class User < ActiveRecord::Base
    attr_accessible :first_name, :last_name

    has_many :posts
    has_many :comments
  end
end

app/controllers/simple_community/application_controller.rb
module SimpleCommunity
  class ApplicationController < ActionController::Base
  end
end

app/controllers/simple_community/comments_controller.rb
require_dependency "simple_community/application_controller"

module SimpleCommunity
  class CommentsController < ApplicationController
    before_filter :fetch_post, :except => [:create, :update]

    # GET /comments
    # GET /comments.json
    def index
      @comments = Comment.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @comments }
      end
    end
  
    # GET /comments/1
    # GET /comments/1.json
    def show
      @comment = Comment.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @comment }
      end
    end
  
    # GET /comments/new
    # GET /comments/new.json
    def new
      @comment = Comment.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @comment }
      end
    end
  
    # GET /comments/1/edit
    def edit
      @comment = Comment.find(params[:id])
    end
  
    # POST /comments
    # POST /comments.json
    def create
      @comment = Comment.new(params[:comment])
  
      respond_to do |format|
        if @comment.save
          flash[:notice] = "Your comment has been created but is currently pending verification."
          format.html { redirect_to @comment.post, notice: 'Comment was successfully created.' }
          format.json { render json: @comment, status: :created, location: @comment }
        else
          format.html { render action: "new" }
          format.json { render json: @comment.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PUT /comments/1
    # PUT /comments/1.json
    def update
      @comment = Comment.find(params[:id])
  
      respond_to do |format|
        if @comment.update_attributes(params[:comment])
          format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @comment.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /comments/1
    # DELETE /comments/1.json
    def destroy
      @comment = Comment.find(params[:id])
      @comment.destroy
  
      respond_to do |format|
        format.html { redirect_to comments_url }
        format.json { head :no_content }
      end
    end

    private

    def fetch_post
      @post = @post || Post.find(params[:post_id])
    end
  end
end

app/controllers/simple_community/posts_controller.rb
require_dependency "simple_community/application_controller"

module SimpleCommunity
  class PostsController < ApplicationController
    # GET /posts
    # GET /posts.json
    def index
      @posts = Post.where("verified = ?", true).all
      @post = Post.new
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @posts }
      end
    end
  
    # GET /posts/1
    # GET /posts/1.json
    def show
      @post = Post.find(params[:id])
      @comments = @post.comments.where("verified = ?", true)
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @post }
      end
    end
  
    # GET /posts/new
    # GET /posts/new.json
    def new
      @post = Post.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @post }
      end
    end
  
    # GET /posts/1/edit
    def edit
      @post = Post.find(params[:id])
    end
  
    # POST /posts
    # POST /posts.json
    def create
      @post = Post.new(params[:post])

      @post.images.clear

      if (params[:post_image]) then
        params[:post_image].each do |image|
          @post.images << SimpleImageBank::Image.find(image)
        end
      end
  
      respond_to do |format|
        if @post.save
          format.html { redirect_to @post, notice: 'Post was successfully created.' }
          format.json { render json: @post, status: :created, location: @post }
        else
          format.html { render action: "new" }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PUT /posts/1
    # PUT /posts/1.json
    def update
      @post = Post.find(params[:id])

      @post.images.clear

      if (params[:post_image]) then
        params[:post_image].each do |image|
          @post.images << SimpleImageBank::Image.find(image)
        end
      end
  
      respond_to do |format|
        if @post.update_attributes(params[:post])
          format.html { redirect_to @post, notice: 'Post was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
      @post = Post.find(params[:id])
      @post.destroy
  
      respond_to do |format|
        format.html { redirect_to posts_url }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/simple_community/application_helper.rb
module SimpleCommunity
  module ApplicationHelper
  	def profile_picture
	  "simple_community/holder_user.jpg"
  	end

  	def user_name
  	  "Mike Hart"
  	end

  	def post_count
	    0
  	end

  	def unverified_post_count
	    0
  	end

  	def get_current_user
	    User.find(1)
  	end

  	def profile_picture_for(user)
	    profile_picture
  	end

  	def path_to_placeholder
	    profile_picture
  	end

    def get_image_bank_for(user)
      SimpleImageBank::ImageBank.find_by_user_id(user.id)
    end
  end
end

app/helpers/simple_community/comments_helper.rb
module SimpleCommunity
  module CommentsHelper
  end
end

app/helpers/simple_community/dashboard_helper.rb
module SimpleCommunity
  module DashboardHelper
  end
end

app/helpers/simple_community/posts_helper.rb
module SimpleCommunity
  module PostsHelper
  end
end

app/views/layouts/simple_community/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimpleCommunity</title>
  <%= stylesheet_link_tag    "simple_community/application", :media => "all" %>
  <%= javascript_include_tag "simple_community/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="row">
    <div class="span2">
	  <div class="well">
        <a href="/users/<%= get_current_user().id %>/edit">
    	    <%= image_tag profile_picture() %>
        </a>
      	<p>Welcome, <%= user_name() %></p>
      	<p>Total posts: <%= post_count() %></p>
      	<p>Unverified posts: <%= unverified_post_count() %></p>
        <%= link_to "New Post", new_post_path, :class => "btn btn-success" %>
	  </div><!-- well -->
    </div><!-- span2 -->
    <div class="span10">
      <%= yield %>
    </div><!-- span10 -->
  </div>
</div>

</body>
</html>

app/views/simple_community/comments/_comment.html.erb
<div class="media">
  <a class="pull-left" href="#">
    <img class="media-object" src="<%= profile_picture_for(comment.user) if comment.user %>" />
  </a>
  <div class="media-body">
    <h4 class="media-heading">
      <% if comment.user then %>
        <%= comment.user.first_name %> <%= comment.user.last_name %>
      <% else %>
        Unknown User
      <% end %>
      </h4>
    <p><%= comment.content %></p>
  </div>
</div>

<div style="clear: both"></div>

app/views/simple_community/comments/_form.html.erb
<%= form_for(@comment, :class => "form", :action => post_comments_path(@post)) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <% @comment.errors.full_messages.each do |msg| %>
        <p class="alert"><%= msg %></p>
      <% end %>
    </div>
  <% end %>

  <%= f.hidden_field :user_id, :value => get_current_user().id %>
  <%= f.hidden_field :post_id, :value => params[:post_id] %>
  <%= f.hidden_field :verified, :value => 0 %>

  <div class="field">
    <%= f.text_area :content %>
  </div>
  <div class="btn-group">
    <%= link_to 'Back', post_path(@post), :class => "btn" %>
    <%= f.submit :class => "btn btn-success" %>
  </div>
<% end %>

app/views/simple_community/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

app/views/simple_community/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>User</th>
    <th>Post</th>
    <th>Verified</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.user_id %></td>
    <td><%= comment.post_id %></td>
    <td><%= comment.verified %></td>
    <td><%= comment.content %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/simple_community/comments/new.html.erb
<h1>Comment on <%= @post.name %></h1>

<%= render 'form' %>

app/views/simple_community/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @comment.user_id %>
</p>

<p>
  <b>Post:</b>
  <%= @comment.post_id %>
</p>

<p>
  <b>Verified:</b>
  <%= @comment.verified %>
</p>

<p>
  <b>Content:</b>
  <%= @comment.content %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/simple_community/posts/_form.html.erb
<div id="simple_image_bank_modal" class="modal hide fade">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>My Image Bank</h3>
  </div>
  <div class="modal-body">
    <% get_image_bank_for(get_current_user).images.each do |image| %>
      <% if (@post.images.include?(image)) then %>
        <%= image_tag image.image.url(:thumb), :id => image.id, :class => "simple_image_bank_thumb selected" %>
      <% else %>
        <%= image_tag image.image.url(:thumb), :id => image.id, :class => "simple_image_bank_thumb" %>
      <% end %>
    <% end %>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" id="simple_image_bank_modal_close">Close</a>
    <a href="#" class="btn btn-primary" id="simple_image_bank_add_selected">Add this image</a>
  </div>
</div>

<%= form_for(@post, :html => { :class => "form_image_addable form form-horizontal" }) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <legend>Basic Details</legend>
    <div class="control-group">
      <%= f.label :name, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :name %>
      </div><!-- controls -->
    </div>
    <div class="control-group">
      <%= f.label :content, :class => "control-label" %>
      <div class="controls">
        <%= f.text_area :content %>
      </div><!-- controls -->
    </div>
    <div class="control-group">
      <%= f.label "Youtube ID", :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :youtube_id %>
      </div><!-- controls -->
    </div>

    <%= f.hidden_field :verified, :value => 0 %>
    <%= f.hidden_field :user_id, :value => get_current_user().id %>
</fieldset>
<fieldset>
  <legend>Images</legend>
  <%= link_to "Add images", "#", :id => "simple_image_bank_display_modal" %>
  <% @post.images.each do |image| %>
    <input type="hidden" name="post_image[]" class="post_image" value="<%= image.id %>" />
  <% end %>
</fieldset>
  <div class="control-group">

      <div class="btn-group controls">
        <%= link_to 'Back', posts_path, :class => "btn" %>
        <%= f.submit "Save", :class => "btn btn-success" %>
      </div>
  </div><!-- control-group -->
<% end %>

app/views/simple_community/posts/_post.html.erb
<div class="media">
  <a class="pull-left" href="#">
  	<% if @post.user %>
	  <img class="media-object" src="<%= profile_picture_for(@post.user) %>" />
    <% else %>
	  <%= image_tag path_to_placeholder(), :class => "media-object" %>
    <% end %>
  </a>
  <div class="media-body">
    <h4 class="media-heading">
      <%= post.name %>
  	</h4>
    <%=raw truncate(post.content, :length => 200) %>
    <br />
    <div class="btn-group">
	  <%= link_to "Comment (" + post.comments.where("verified = ?", true).size.to_s + ")", new_post_comment_path(post), :class => "btn" %>
	  <%= link_to "Read more", post, :class => "btn" %>
    </div><!-- btn-group -->
  </div><!-- media-body -->
</div><!-- media -->

<div style="clear: both;"></div>

app/views/simple_community/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/simple_community/posts/index.html.erb
<%= content_tag(:strong, "There are currently no posts on display.") unless @posts.size > 0 %>

<% @posts.each do |post| %>
  <%= render post, :locals => { :post => post } %>
<% end %>

app/views/simple_community/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

app/views/simple_community/posts/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @post.name %></h1>

<% if (!@post.verified) then %>
	<p class="alert alert-warning">This post is pending verification</p>
<% end %>

<p class="<% if (@post.images.size > 0 || @post.youtube_id) %>has_images<% end %>"><%=raw @post.content %></p>

<% if (@post.images.size > 0 || @post.youtube_id) then %>
	<span class="post_images">
		<% if (@post.youtube_id && @post.youtube_id != "") then %>
			<iframe src="http://www.youtube.com/embed/<%= @post.youtube_id %>" frameborder="0" allowfullscreen></iframe>
		<% end %>
		<% @post.images.each do |image| %>
			<%= image_tag image.image.url(:medium) %>
		<% end %>
	</span><!-- post_images -->
<% end %>

<%= content_tag(:strong, "There are currently no comments for this post.") unless @comments.size > 0 %>

<%= render @comments %>

<div class="btn-group">
	<%= link_to 'Back to Posts', posts_path, :class => "btn" %>
	<%= link_to 'Edit', edit_post_path(@post), :class => "btn" if @post.is_owner?(get_current_user().id) %>
	<%= link_to 'Comment', new_post_comment_path(@post), :class => "btn" if @post.verified %>
</div><!-- btn-group -->